### ISSUE TITLE
New Create Primitive operator for draw object on surface.

### ISSUE THREAD

**Issue by hansnolte** [NevilArt/BsMax#22]
Hi NevilArt,

Is it working yet?
If so, how?
Can you please post a short description.

Many greetings
Hans

**Comment by NevilArt** [comment]
Hi Dear Hans

I made a new draw primitive tool but unfortunately it not complete yet. I need some more math knowledge for finish this task.
Currently I`m working an animation tool that help character walks along a path on a surface. then I`ll be back to this task again.
For now only objects that have Radius and Height can drawn on surface and object with Width and Length still use old operator.

Thanks. Nevil.

**Comment by hansnolte** [comment]
Hi Nevil,

many thanks for your answer.
Can't wait to try the animation tool.

Many greetings
Hans
