### ISSUE TITLE
Problem occurs when sending to backburner on Linux.

### ISSUE THREAD

**Issue by frkntlr** [NevilArt/BsMax#24]
Even if it gives an error in sending, it is visible on the backburner monitor.

![image](https://user-images.githubusercontent.com/14142761/155519329-47df3611-8497-407a-a4ca-3f183055881e.png)
![image](https://user-images.githubusercontent.com/14142761/155519379-04d7882d-50c7-498f-9178-6ae9dbcac0a6.png)

Still, I wanted to send the error given below.
No problem when rendering.It can render to the specified path.

```
Python: Traceback (most recent call last):
  File "/home/atalar/.config/blender/3.0/scripts/addons/BsMax_2_80-master/tools/internal/render/backburner.py", line 436, in execute
    script = open(preset_path + file_name).read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/atalar/.config/blender/3.0/config\\BsMax\\Backburner.ini'

location: <unknown location>:-1


```

**Comment by NevilArt** [comment]
Hi,

I got it. Ill work on it on this weekend.

Thank you for report.

**Comment by NevilArt** [comment]
I think problem has solved.
Can you check the last Update and let me know is it works fine or not?

**Comment by frkntlr** [comment]
Of course, I'll take a look when I'm available.
