### ISSUE TITLE
Problem with enabling the add-on

### ISSUE THREAD

**Issue by RedFudge** [NevilArt/BsMax#25]
When enabling the add-on from the add-ons tab, I get the following error. Any idea how to resolve?
Thanks

![image](https://user-images.githubusercontent.com/102590704/160591025-f8d3cb7e-a343-4ff7-b738-5984016f1e7b.png)

**Comment by NevilArt** [comment]
Looks like you are using a very old version of BsMax.
Can you download the latest update and let me know is that problem solved or not?
