### ISSUE TITLE
Navigation Modifier Key Behaviour - Please allow overriding current mode

### ISSUE THREAD

**Issue by datacain** [NevilArt/BsMax#26]
First, thanks for this addon!
I've just came from Max, and this is helping greatly!

However I noticed a small issue that catches me out constantly with Navigation.

In 3Ds Max I don't have to release the middle mouse button (MMB) to switch between PAN, ROTATE, etc.
I just continue to hold the MMB down and then press/hold/release the modifier keys (ie. ALT/CTRL/SHIFT) as required, and it will happily switch from pan to rotate, and back.

However with the current BsMax version I have to release the MMB every time I want to change from one mode to another.
To switch from PAN mode, I have to release MMB, then hold ALT before pressing MMB again to activate ROTATE; likewise to switch back to PAN, I have to release MMB+ALT and then press MMB again.

Thank you!

**Comment by NevilArt** [comment]
Hi Dear Aaron.

I have years of experience with 3DsMax and travel to Blender for the same reason as you did. I`m happy the BsMax helps many people. 

I`m already knew the issue with navigation and unfortunately I do not have solution for it yet. but it is in my schedule and hope to be able to fix it some day soon.
