### ISSUE TITLE
This addon is the best ever!

### ISSUE THREAD

**Issue by Kozzren** [NevilArt/BsMax#28]
I just wanted to say a HUGE thank you for making this possible, I have been using 3ds max for 2 years straight and always wanted to move to blender, but it was just missing things i was used too. You have added a lot of them but i was wondering if you will be able to change the hotkeys your self to some of the commands to make it a bit faster to work with. In my current workflow i usually have shift + D for detach and shift + numpad2 for new layer/collections and shift + numpad3 for removing empty layers/collections. Something like those would be incredible to have so much so that i could fully switch to blender just about. I was also wondering if it were possible to bring over the line tools from max to draw splines on faces or use snapping to draw splines on faces connecting vertex's etc. I am very excited to see what you do with this addon.

**Comment by NevilArt** [comment]
Hi  Dear Kozzren

I`m happy to here that BsMax is useful for many people. adding short keys is not easy decision. as I try to mimic 3Dsmax keys in blender at the same time I`m try to keep blenders original keys too much as possible. for example 'Shift + D' is duplicate in blender if I change it to 'Detach' there is not an alternative for it. add shortcut for detach tool is good idea but we have to use free key such as 'Ctrl + Shift + D' for add and remove collection I had to think about it. and the snap for line yes that is a missing and frequently requested future and had to work on it too.
