### ISSUE TITLE
3DsMax Hotkey for Maya.

### ISSUE THREAD

**Issue by SadeqGitHub** [NevilArt/BsMax#29]
Hi, your BsMax for blender helped me a lot. Is there really a hotkey for Maya? I'm using 3dsMax for 8 years on any 3Ds softwares. Thank you for your time. =]

**Comment by NevilArt** [comment]
Hi, yeah its possible to add Maya`s key-maps too. but I will need some help to improve that part.

**Comment by SadeqGitHub** [comment]
> Hi yeah its possible to add Mayas key-maps too. but I will need some help to improve that part. If you be able send me list of key maps and action in Maya Ill add much I can in each update. you don`t have too send a full list of short cuts to me. just a few each time.

As same as Blender perhaps?

Most common like:

Object:
1. Selection (Mouse+Left click)etc.
2. Deselect (Mouse+Right click)etc.
2. Select+All
3. Rotate, Axis, Scale (Q,W,E) etc.
4. Zoom to object. (Z)

Viewport:
1. Zoom
2. Panning (X, Y, Z Axis)etc.
3. Rotate

These are most common used for animation. Not to mention modelling. Perhaps these would help. Thanks.

**Comment by NevilArt** [comment]
I started to apply key maps but your note is not clear enough for me.

Object:
   1. Selection (Left mouse button 'LMB') set select that mean deselect other and just select clicked one.
   2. Add to selection 'Shift + LMB' ?
   3. Remove From Selected 'RMB' ?
   4. Select all witch keys? 'Ctrl + A'
   5. Zoom to object (Framing on object) 'F' ? Already exist

Viewport:

   1. Zoom 'Alt + RMB' Already exist
   2. Pann 'Alt + MMB' Already exist
   3. Rotate 'Alt + LMB' Already exist

![Maya](https://user-images.githubusercontent.com/36098311/171993372-687ab163-6082-4a8a-86f5-ce3761b03a28.JPG)

please send me requested key maps in this style

'short name of the action' + ' Key map' + 'type (Pressed, Hold, Released, Drag ....)' + 'maybe some explanation'

e.g.   Frame 'F' 'press' Zoom on selected objects
e.g.   View Pan 'Alt + MMB' 'Drag' pan the view .......

**Comment by NevilArt** [comment]
Sorry. But Blender is only 3D animation software I am working on.
