### ISSUE TITLE
Does BsMax work in Windows 11?

### ISSUE THREAD

**Issue by KenTanker0us** [NevilArt/BsMax#33]
Hi Naser, thank you so much for BsMax. I have been using it happily for a long time now in blender 3.4 on Windows 10.

I just built a new machine and it has Windows 11. Still blender 3.4. I am getting an error when I try to activate the addon.

![BsMax error 2023-05-13 133823](https://github.com/NevilArt/BsMax/assets/133395569/49c1e7a9-319f-4318-bb4e-948e93a57644)

I hope I didn't do anything wrong; I just installed it like I always did. Any help and advice would be most welcome!

In the meantime, the .py script will open BsMax temporarily (until I close blender) and I can submit to Backburner.

Thank you for your generosity in sharing this wonderful tool.

**Comment by NevilArt** [comment]
Hi

I test the BsMax on Blender 3.4.1 and 3.5.1 on windows 11 64 and add-on works without any problem.
Reset the blender to factory and install BsMax again and let me know does is works or not.

**Comment by KenTanker0us** [comment]
Yes! That was it. Thank you so much for BsMax.
