### ISSUE TITLE
<UI BUG>It will cause trouble when use light color theme

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [NevilArt/BsMax#34]
Yes, it will become between red and black.

But....

When you use white theme .It changes to red then becomes black not the color it has start.

![image](https://github.com/NevilArt/BsMax/assets/65578116/a9f2b6a7-c885-45fc-97ad-a136355bebe4)

![image](https://github.com/NevilArt/BsMax/assets/65578116/aca9eebf-2589-49c3-8668-684729120ac9)

We can only change the theme again to fix....

**Comment by BUGProtectionAssociation** [comment]
![image](https://github.com/NevilArt/BsMax/assets/65578116/8922c595-b9fb-4b7d-b0c0-0b417be8ad05)

Text will can't read because this

**Comment by NevilArt** [comment]
OK, I got it.
I know what is the problem. I wrote the code base on the default theme years ego.
Need to do some changes to store and restore active theme value.

**Comment by NevilArt** [comment]
I find a good solution and fix this issue. you can get it on next update.
