### ISSUE TITLE
Selection Set 

### ISSUE THREAD

**Issue by hashman63** [NevilArt/BsMax#36]
Hi! Nice addon. I would suggest you to make a function to hide not selected sets. so not used controls rig, hid and do not interfere with the work of the animator.
And I would also make the button color highlighting the active set.
Now it is not very conveniently implemented multiselect function (you need to press/press the plus button). It will be much more convenient if the multiselect function will be realized with the Shift key.
I hope you will appreciate this suggestion and make it in the next update.

**Comment by NevilArt** [comment]
Thank you for ideas.
I have some suggestion from another friend too.
Ideas is good. I will write a new version of the selection set Advance than the current one.
I will create completely new tool, then feel free and let me know any ideas do you have.

**Comment by NevilArt** [comment]
For now Hold shift for add selection and Auto hide option added.
