### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Gusher** [NevilArt/BsMax#37]
![mockup](https://github.com/NevilArt/BsMax/assets/261646/155816a1-a3aa-4ef8-bd9f-5bf4eebeb91f)
Can you add ability to change viewcube gizmo to any 3d custom gizmo?
Also, option in plugin settings to choose a 3dsmax style UI theme? Also, add a side panel!

**Comment by NevilArt** [comment]
Oh Yeah. I love this idea.

**Comment by Gusher** [comment]
Another suggestion....  ability to scale quad menu and pie menus as well.....have blender interface scaled to 1.50 but addon UI doesn't scale to match desired look...
![Screenshot 2024-01-03 153413](https://github.com/NevilArt/BsMax/assets/261646/57b24f87-82fc-48a7-ade4-31b8e74cc06d)

**Comment by NevilArt** [comment]
![Command panel](https://github.com/NevilArt/BsMax/assets/36098311/b29116c9-addb-4e9d-8db9-076e9f74268d)

Result is going to be more funny any and sweeter than I aspect.

**Comment by NevilArt** [comment]
![menu scale](https://github.com/NevilArt/BsMax/assets/36098311/4c38a835-7ca6-4480-80b7-fdceb6090213)

There is an option for scale the float menu.

**Comment by Gusher** [comment]
Now it's beginning to feel very Max friendly!.... a very smooth transition for those who cannot afford the license.... have you seen the Maya addon by Form Affinity? Looks impressive..
