### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Aizen-Sousuke** [NevilArt/BsMax#38]
![image](https://github.com/NevilArt/BsMax/assets/46592941/dd8ca4ba-48c6-448d-92de-8ea8d94c9a84)

**Comment by smugga** [comment]
I have similar error. Blender 4.0

**Comment by NevilArt** [comment]
Hi. Thanks for report the issue.

For both issue.
1. Make sure you have the latest version of BsMax.
2. Reset blender to factory mode and re open it and then install BsMax again.

Please Let me know is it worked in this way or not.

**Comment by Aizen-Sousuke** [comment]
Thanks for your answer.
I set the  blender language to English and install BsMax.
issue was settled.

**Comment by NevilArt** [comment]
Good.
Now I know changing the language caused the error.
I'll work on it to fix.
