### ISSUE TITLE
Install error Blender 4.0 and Maya Key Bind is broken

### ISSUE THREAD

**Issue by DanTreeman** [NevilArt/BsMax#39]
I just figured out that the R key in the Maya Preset, which is scale, is now Blender rotate. I cannot scale at all anymore.  So, I uninstalled the addon and reinstalled it only to receive errors codes. Basically, it no longer works.

Edit: got the addon to work, but still cannot scale.

**Comment by DanTreeman** [comment]
Resize is completely broken in object mode and edit mode.

In Maya as you know that resize/scale is R. In Blender, in object mode, R is now rotate and S is scale in edit mode only.

**Comment by DanTreeman** [comment]
It is the latest version.

**Comment by DanTreeman** [comment]
Somehow I got it working. I had to rest my preferences to default. But for troubleshooting, it should be tested on other machines and versions of blender.

**Comment by DanTreeman** [comment]
Can you disable the R for Rotate, it caused a conflict, There was a conflict there. I had to fix, but it would be nice to be available from default. In the Maya keybinds.

**Comment by DanTreeman** [comment]
Both in object and edit modes

**Comment by NevilArt** [comment]
Hi
Thank you for report the issue.
Yeah I see that and it will be fixed for next update.
Unfortunately I do not have feedback for Maya part.
If you be able to continue report the missing part for BsMax`s Maya part. I can work on those too.

**Comment by NevilArt** [comment]
You can check the update version now
