### ISSUE TITLE
Apply Bevel Modifer on BSMax primitive = crash

### ISSUE THREAD

**Issue by thorn-neverwake** [NevilArt/BsMax#41]
**Describe the bug**
BSMax cylinder is created, with SLICE activated. 

**To Reproduce**
[cylinder slice.zip](https://github.com/NevilArt/BsMax/files/15227135/cylinder.slice.zip)

1. Open attached file.
2. Select cylinder object.
3. Apply Bevel modifier
4. See crash.

**Expected behavior**
Obviously, should not crash. 

- If slice is NOT on, no crash.
- Alternative: create a new BSMax cylinder, with NO slice. Apply bevel = no crash, it's fine. Now checkbox SLICE on, and blender instantly crashes.

**Screenshots**

**OS and Version (please complete the following information):**
 - OS: Windows 10
 - Blender Version 4.1

Hope this helps :)

thorn

**Comment by NevilArt** [comment]
Thank you for report the bug.

Yes I saw the issue. its happens when Cylinder has Slice and Cap Segment at the same time. I checked the cylinder topology and found a double edge in lower plate that that one who did not marked as sharp edge. Ill try to fixed it soon.

**Comment by NevilArt** [comment]
This bug has been fixed.
